apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: concentrey-com
  labels:
    {{- include "soffortbackend.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.gateway.tlsSecretName }}
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.gateway.hostname }}
