apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soffortbackend.fullname" . }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.approval.workloadClientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.identity.tenantId | quote }}
  labels:
    {{- include "soffortbackend.labels" . | nindent 4 }}
automountServiceAccountToken: false
