apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soffortbackend.fullname" . }}
  labels:
    {{- include "soffortbackend.labels" . | nindent 4 }}
automountServiceAccountToken: false

